### ISSUE TITLE
ダッシュボードで「計測ボタン」クリックで計測Jobが登録され、計測Jobタスク一覧が更新されるようにする

### ISSUE THREAD

**Issue by chimame** [ateam-dev/web-speed-hackathon-2021-leaderboard#15]

**Comment by aiji42** [comment]
UIはできている。
ジョブのキックがまだ。

**Comment by chimame** [comment]
tokenは[Bash](https://cloud.google.com/iap/docs/authentication-howto?hl=ja#iap_make_request-nodejs)からでも作れるのでできるっちゃできる

**Comment by chimame** [comment]
いいものがあったので使ってみる

https://github.com/sagi/workers-jwt

**Comment by aiji42** [comment]
おーこんなのあるんすね。
以前、next.jsのmiddlewareでJWT処理させるために、joseで頑張ったのをおもいだしましたわ。
