### ISSUE TITLE
ダッシュボード

### ISSUE THREAD

**Issue by aiji42** [ateam-dev/web-speed-hackathon-2021-leaderboard#5]
- supabase realtimeを利用

- 表示内容
    - スコア
        - ランキング
    - グラフ
    - 再計測リクエストボタン

**Comment by chimame** [comment]
画面イメージ
![image](https://user-images.githubusercontent.com/7520815/161877949-18a825bd-e761-4417-b8d4-60a5cd66fe2a.png)

**Comment by chimame** [comment]
上記画面イメージで機能を細分化

- [ ] UIを構築
- [ ] 画面の初期表示時に以下の情報が表示されること
  - [ ] 自チームの計測先URLが表示される
  - [ ] 全チームの計測Jobタスク一覧が表示される
  - [ ] 全チームのスコアがグラフで表示される
- [ ] 「計測ボタン」クリックで計測Jobが登録され、計測Jobタスクが更新される
- [ ] 以下の情報は他チームで登録されたら更新される（自動更新）
  - [ ] Jobタスク
  - [ ] スコアグラフ
